Create tox xblock and add basic functionality
Stanford-Online/xblock-adaptive-numeric-input pull request #1
Opened 2017-02-02 16:17 UTC by caseylitton

@stvstnfrd initial PR for adaptive numeric xblock.  Pending tests.py and validate_field_data function.   The major difference is the scoring functions starting with _compute_score.  The rest of the code is pretty standard and taken from other xblocks.  

There are a bunch of comments in submit function explaining the different fields.

2017-02-02 16:18 UTC, caseylitton commented
Needs Tests

2017-02-27 21:29 UTC, stvstnfrd requested changes

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +"""TO-DO: Write a description of what this XBlock is."""
TODO.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +    if value:
What if `value` is falsey? Could this value ever be `0`? If so, this block wouldn't be entered.

We should just try to cast it...

```python
def _get_float(value):
    try:
        return float(value)
    except ValueError:
        return None
```

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +FEEDBACK_MAP = {
This seems fairly verbose, especially when they all do roughly the same thing.

Ideally, we can intuit the formatting from the data type.

```python
SUPPORTED_KEYWORDS = [
    '%%STUDENT_ANSWER%%',
    # ...
]

def substitute(self, keyword, feedback):
    value = getattr(self, keyword, None)
    if value is None or keyword not in feedback:
        return feedback
    if isinstance(value, Float):
        value = "{0:.0f}".format(value)
    else:
        value = unicode(value)
    feedback = feedback.replace(keyword, value)
    return feedback
    
def get_feedback_from_credit_dict(self, credit_dict):
    # ...
    for keyword in SUPPORTED_KEYWORDS:
        feedback = self.substitute(keyword, feedback)
    # ...
```

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +FEEDBACK_MAP = {
NB: I know the one exception to the above is `STUDENT_ERROR_PERCENT` which currently extends to a single decimal place. But as discussed F2F, I don't think we need this level of accuracy. If anything, I'd argue that we should even _further_ fuzz this value; we shouldn't tell people exactly how close they are. Doing so (especially combined with the fact that answers can be "close") means any problem can be solved simply by making one attempt then deduced via some simple algebra.

Actually given that, I don't think we should ever display this. Instead, we should simply tell them what range they fell into:

> Your answer is within 10% of the correct answer.

If instructors want to provide more granular messages, they can configure tighter tolerances for the varying credit groups.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +    TO-DO: document what your XBlock does.
TODO

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +                <adaptivenumericinput/>
Please provide some additional examples.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +    full_credit_list = List(
What's an example where you would want multiple correct answers for numerical proximity?

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +                'tolerance_percent': '1',
Should the default simply be 0% (i.e., force a completely correct response unless otherwise noted)?

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/private/view.html
> +            <input type='number' class="student_answer" value="{self.student_answer}">
Don't pass `self`; instead just pass `student_answer` to the renderer.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/private/view.html
> +            Hint
What are our globalization concerns?

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/private/view.js
> +        // Student Answer
This is superfluous.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/private/view.js
> +        // Feedback
This is superfluous.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/private/view.js
> +        feedback.addClass(new_class);
Why are we adding this class to multiple elements?
Can we just apply it to a common parent?

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +                'feedback': 'Did you convert C to F?'
Trailing comma.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        # Validate these too to check for errors.
Is this a TODO?

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +    # Scoring
Superfluous.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +                'max_value': Credit.full.value
Trailing comma.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        # Full Credit
Superfluous.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        # Half Credit
Superfluous.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        # Check for exact answer
Superfluous.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        #  Zero Credit
Superfluous.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +                k.get("tolerance_percent", None)
Single quotes.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +            if tolerance_percent:
What if tolerance is zero?

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        sorted_hints_adaptive_list = sorted(
Can we avoid sorting these lists on each submission/pageload?

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +    # Messages
This message itself is superfluous.

If you're finding that this file is becoming so large and has several related categories of methods, we should consider splitting this class definition out with mixins.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        if self.weight == 0:
Isn't this a pointless block?

`result` will always be set to some other value later on, if not in the `if`, then in the `else.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/private/view.css
> +
I think this file technically ends with 2 newlines, not just one.

2017-02-27 21:29 UTC, stvstnfrd commented on package.json
> +
Extra newline.

2017-02-27 21:29 UTC, stvstnfrd commented on manage.py
> +
Extra newline.

2017-02-27 21:29 UTC, stvstnfrd commented on adaptivenumericinput/public/view.less
> +
Extra newline.

2017-03-03 01:15 UTC, caseylitton commented on adaptivenumericinput/adaptivenumericinput.py
> +FEEDBACK_MAP = {
STUDENT_ERROR_PERCENT is not the same as TOLERANCE_PERCENT.  As we discussed F2F, I limited the TOLERANCE_PERCENT to integer values based on your concerns.  

Our main goal now is code review.  We shouldn't deviate with discussions about what instructors think or want.  I'm planning to meet with course ops at an appropriate time to consider the content.  You are of course welcome to join those conversations and voice your opinions on the matter.   Prior to that meeting I will create some documentation detailing the variables and how I see them being used.  Along with more examples per a different comment.  This will be the start of the previously discussed user docs.   

I'm holding off making any changes to the FEEDBACK_MAP until finalizing the key/value pairs with course ops.  It will be easy to remove the lambda functions then.  I placed a TODO comment so I don't forget.  

Personally, I liked that each key had a function attached to it for formatting.  This avoids the need to hunt through code to find if and when numbers are being rounded.  I’m sure there are multiple ways to accomplish this so we can discuss when needed.

2017-03-03 01:15 UTC, caseylitton commented on adaptivenumericinput/adaptivenumericinput.py
> +    full_credit_list = List(
The one shown in the default is an example of how it would be used.  We are allowing instructors to provide custom adaptive feedback.

2017-03-03 01:15 UTC, caseylitton commented on adaptivenumericinput/adaptivenumericinput.py
> +                'tolerance_percent': '1',
These are the standard defaults that show up in settings.  You and Monica told me to make a simple example for studio settings.   Please make sure the temperature example is acceptable.

2017-03-03 01:15 UTC, caseylitton commented on adaptivenumericinput/adaptivenumericinput.py
> +        # Validate these too to check for errors.
Yes, once we nail down the code I can write tests for these.

2017-03-03 01:16 UTC, caseylitton commented on adaptivenumericinput/adaptivenumericinput.py
> +            if tolerance_percent:
Zero tolerances are not considered when searching for a tolerance_percent match.

2017-03-03 01:16 UTC, caseylitton commented on adaptivenumericinput/adaptivenumericinput.py
> +        sorted_hints_adaptive_list = sorted(
I thought we discussed this at one point and didn't come up with a satisfactory conclusion.  The questions is where, in studio when the instructor save, maybe on page refresh in student_view?

2017-03-03 01:16 UTC, caseylitton commented on adaptivenumericinput/adaptivenumericinput.py
> +        if self.weight == 0:
Nope, it was a typo.  Should be if/elif/

2017-03-03 01:16 UTC, caseylitton commented on adaptivenumericinput/adaptivenumericinput.py
> +                <adaptivenumericinput/>
TBD

2017-03-03 01:16 UTC, caseylitton commented on adaptivenumericinput/private/view.html
> +            Hint
It uses up finite resources more quickly and increases world carbon dioxide emissions.  You'll need to be more specific...?

2017-03-03 01:16 UTC, caseylitton commented on adaptivenumericinput/private/view.js
> +        feedback.addClass(new_class);
Yes, fixed.

2017-03-03 01:18 UTC, caseylitton commented
@stvstnfrd Anything without a comment will be fixed in the next PR.  I will also recheck what happens with zero values for certain parameters.

2017-03-15 19:59 UTC, stvstnfrd commented
@gbruhns Would you mind clarifying the user story here?

I think there's been some confusion (at least on my part) on what we're trying to accomplish with this XBlock. The original intent was to provide a specific use case for an instructor's course. But I'm led to believe now that this course has finished, so this XBlock is meant to be more general purpose.

I know some of this has been covered in F2F conversations between Casey, Monica, and yourself, but without documentation, it's difficult to review the code for correctness.

2017-03-16 18:31 UTC, gbruhns commented
@stvstnfrd the original story/description of the feature I put in Trello was for a general use case that would cover the original request (which was more specific and would not have been as flexible to cover more general use cases, and yes, the course the original request came for ran this Winter quarter). The intent is still to make it easier to set up these types of questions so you don't have to know python to modify the default question type (Problem with Adaptive Hint under the Advanced Problems).

Hope that helps.

2017-03-21 21:22 UTC, caseylitton commented
@stvstnfrd @caesar2164 PR for adaptive numeric feedback.  Per our meetings a good deal of the xblock was refactored so the commits were squashed. All of the previous comments were addressed or irrelevant after the changes.  There is a TODO in verification of settings and tests will need to be written.

2017-03-27 19:18 UTC, stvstnfrd commented
@caseylitton Regardless of how much may have changed, please do not squash PRs mid-review.

While a lot of the Python may have changed, I suspect much of the supporting infrastructure (tox, .travis, CSS, etc.) is unchanged. Regardless, now I have to read through the entire contents of this repo, again, instead of just reviewing the delta. 

We don't really gain anything by squashing prematurely, as the PR still shows the entire changes by default. But once squashed, I can't see the progression and it leads to a lot of unnecessary re-review.

Thanks.

2017-03-27 19:19 UTC, stvstnfrd commented
Also, go ahead and write tests and address any outstanding TODOs.
I'll review again once everything is in place.

2017-04-19 22:11 UTC, caseylitton commented
retest this please

2017-07-19 21:46 UTC, stvstnfrd requested changes

2017-07-19 21:46 UTC, stvstnfrd commented on .gitignore
> +.ropeproject
Curiously, where did this come from?

2017-07-19 21:46 UTC, stvstnfrd commented on .travis.yml
> +      - 'master'
Will this affect how it's (or not) run against PRs?

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +    An XBlock where instructors can provide adaptive feedback for numeric
This block should be unindented.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +
Remove newline, since these are all stdlib imports.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +
Remove newline?

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +    # Returns percent and absolute error of 'answer' from 'actual_answer'
This should be a proper docstring with triple quotes.

2017-07-19 21:46 UTC, stvstnfrd commented on GruntFile.js
> +module.exports = function (grunt) {
I'm assuming this is all boilerplate and there's nothing of note?

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        'absoltue_error.html',
typo.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        'temp_conversion.html',
Can we call this `temperature` to distinguish it from `temporary`?

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        'default_common_mistake.html',
These should be XML files.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        scenario = open(dir_path + '/scenarios/' + scenario_file, 'r')
You should always open files in a `with` block, so that they are automatically closed.

```python
with open('foo.bar', 'r') as scenario:
    scenarios += scenario.read()
```

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +    scenarios_string = '''<sequence_demo>{scenarios}</sequence_demo>'''.format(
Why the triple quotes?
We should just use a single pair of double-quotes (for an interpolated string).

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        scenario = open(dir_path + '/scenarios/' + scenario_file, 'r')
Also, use string formatting instead of concatenation.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        scenarios += scenario.read()
Actually, we should avoid appending strings w/in a loop; it's memory intensive.
Instead, let's use a list, which we can reduce at the end.

```python
output = [
    '<sequence_demo>',
    '<adaptivenumericinput />',
]
for scenario_file in scenario_files:
    scenario = open(dir_path + '/scenarios/' + scenario_file, 'r')
    output.append(scenario.read())
output.append('</sequence_demo>')
output = ''.join(output)
return output
```

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        #  pylint: disable=dangerous-default-value, too-many-arguments
Don't disable this (`dangerous-default-value`); it's a legitimate warning that could cause bugs, as is.

Instead, defaults should be `None`, then we can coalesce to an empty collection:

```python
def foo(bar=None):
    bar = bar or []
```

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +            result = 'hidden'
Per the convention you're using in both `get_css_hint_button_display` and `get_css_hide_submit`,
let's initialize the value to this.

```python
result = 'hidden'
if self.display_correctness:
    result = ''
return result
```

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +            if self.credit_dict.get('feedback') is not None:
This should be simplified as:

```python
feedback_message = self.credit_dict.get('feedback', self.feedback_default)
```

to replace lines 370->372

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +                credit_key = str(key.lower()[2:-2])
`str` is superfluous. This can just be:

```python
credit_key = key.lower()[2:-2]
```

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +                if value is None:
Can this block be simplified as `value = self.credit_dict.get(credit_key, value)`?

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +            feedback_label = 'Correct:'
This should be i18n'ed.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +                feedback_label = 'Incorrect:'
This should be i18n'ed.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +            hint_mod = self.hint_counter % hints_total
Can we just say

```python
hint_number = (self.hint_counter % hints_total) + 1
```

That way we can avoid performing a mathematical operation w/in the string format below.
Also, the variable name here makes it slightly more clear.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +            self=self,
We should avoid passing `self` directly (it's huge),
and instead just pass the members that we need.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +            feedback_label='',
For all of these values that are hard-coded to empty strings, do we need to pass them in at all?
Can we just omit them?

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +    # Handlers to perform actions
Let's drop the superfluous comment.
The `handler` decorator on the `submit` method should make the intent clear here.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +            return {'status': 'success'}
I agree w/ not negatively impacting the user, but could this still return `status`=`error`?
What effect would that have?

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +            # Used attempts 'out of' message in settings
It looks like most of these comments here (in this dict) are just explaining what the methods do.
Assuming the text is necessary, we should move them to the docstrings of the relevant methods.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        # Clear previous feedback_message
It looks like most of these comments in the method are just repeating what the code is already doing/saying and can be dropped.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/private/view.html
> +            Hint
This should be globalized.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +    # Credit Dict
This comment is superfluous since each method includes the substring `credit_dict` directly in its name.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +            msg = AdaptiveNumericInput.generate_validation_message(
s/msg/message/

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        cp_credit_dict = {
Can we drop the abbreviation for something a bit more clear?
`credit_dict_copy` or some such?

FWIW: I'm not really a fan of `credit_dict`, as is.
We should try to avoid embedding datatypes into variable names.

I'd lean more toward something like `credit_configuration` or even just `configuration`.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +            high_score_list.sort(key=lambda x: x['error_absolute'])
One concern here is that this means we'll be sorting this list twice _each_ time any user submits a response.
Since this list rarely ever changes and would always be static among all users, we should find a way to cache this. Let's talk more offline.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        high_score_list = self.get_credit_dicts_score_list()
See other note about not embedding datatype into variable names:
 `s/high_score_list/high_scores/`

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +            # Check for exact answer and force full credit but keep feedback
Similar to elsewhere, these comments in this method don't appear to add to the conversation.

Comments should explain _why_ when it's not obvious and rarely should they explain _what_ code is doing (the code should do that itself).

"check for exact answer" is nearly identical to `if student_answer_float == self.instructor_answer:`

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        # Percentage error arbitraily has priority over absolute error
typo

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +                round(error_percent, 6) >= round(actual_percent_error, 6)):
What is 6? Should that be a constant instead of a (hard-coded) magic number?

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +    # Scenarios you'd like to see in the
This looks to be repeating the docstring?

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        score_list = []
s/score_list/scores/

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/private/view.html
> +        <button class="check Submit {hide_submit_class}" data-checking="Checking..." data-value="Submit">
Needs i18n.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/private/view.html
> +        <button class="hint {hintdisplay_class}" data-value="Hint">
Needs i18n.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/private/view.html
> +        <button class="save {hide_submit_class}" data-value="Save">
Needs i18n.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/private/view.js
> +                buttonSubmit.text('Checkingvjjasldfk;as');
Typo?

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/private/view.js
> +        buttonSubmit.text('Checking...');
Needs i18n.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/private/view.js
> +            message: 'Submitting...',
Needs i18n.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/private/view.js
> +                buttonSubmit.text('Submit');
Needs i18n.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/private/view.js
> +        buttonSave.text('Checking...');
Needs i18n.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/private/view.js
> +            message: 'Saving...',
Needs i18n.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/private/view.js
> +                buttonSave.text('Save');
Needs i18n.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/private/view.js
> +            message: 'Hint',
Needs i18n.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/private/view.js
> +    studentAnswer.on('keydown', function() {
Could we just name this anonymous function and then drop the comment below?

```javascript
studentAnswer.on('keydown', function resetMessages() {
    // ...
});
```

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/private/view.less
> +    &.correct .feedback-text {
It looks like we could better leverage `less` and nest these style rules correspondingly:

```less
.capa_inputtype {
  &.correct {
    feedback-label {
      color: #1e9348;
    }
    feedback-text {
      color: #1e9348;
    }
  }
}
```

etc...

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/scenarios/bakers_dozen.html
> +        credit_list="[
These files all look over-indented (8 spaces instead of 4)

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/test_data/validate_field_data.json
> +
Superfluous newline.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +Module To Test AdaptiveNumericInput
Are these running on travis-ci?

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +        # actual_answer, answer, result(absolute_error, percent_error))
These labels could be dropped, as their explained via the method arguments below.
It's one less thing to maintain, should these values be updated.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +    def test__answer_error(
`s/test__/test_/`

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +    def test__get_float(self, value, result):
`s/test__/test_/`

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +    def test__read_scenario_files(self):
`s/test__/test_/`

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +        self.assertEqual(test_str, test_result[0:len(test_str)])
I don't think this is checking what it says it's checking.

If it's only looking at the first `len(test_str)` chars, then it's only examining the part that's hard-coded and not actually checking that additional files are being read from disk.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +        print self.xblock.prompt
Drop the debug statement.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +        prompt_str = '<h2>Default Example: Percent error feedback<h2>'\
Use Python's implied string concatenation over slashes:

```python
prompt = (
    'Line 1 '
    'Line 2 '
)
```

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +        prompt_str = '<h2>Default Example: Percent error feedback<h2>'\
Let's just call this `prompt`.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +            ' ranges were added in settings Credit Dictionaries field '\
Remove the leading space.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +            'Your answers have been saved but not scoreed. '
typo.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +        self.assertIsNotNone(test_result.get('score'))
This is superfluous;
if we assert that the score is `1.0`,
we don't also need to to assert that it's not `None`.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +        # pylint: disable=invalid-name, protected-access
What's invalid about the name?

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +        # pylint: disable=invalid-name, protected-access
Which member is protected?

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +            type(test_result),
Why are we checking data types, in addition to values?

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +    student_answer_float = Float(
Why are we storing two copies of the student_answer?
- `student_answer`
- `student_answer_float`

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/adaptivenumericinput.py
> +        'prompt',
Since the order of this collection doesn't matter,
let's alphabetize it.

2017-07-19 21:46 UTC, stvstnfrd commented on tox.ini
> +    {envpython} manage.py test --cover-xml
Wait, doesn't this mean we're running the test suite twice?

2017-07-19 21:46 UTC, stvstnfrd commented on tox.ini
> +commands = {envpython} manage.py test --exe {posargs}
Should we have this on all `commands` sections?

2017-07-19 21:46 UTC, stvstnfrd commented on setup.py
> +        'mako',
What needs mako?

2017-07-19 21:46 UTC, stvstnfrd commented on setup.py
> +        'enum34',
What needs this?

2017-07-19 21:46 UTC, stvstnfrd commented on setup.py
> +        'coverage',
Can we alphabetize this list?

2017-07-19 21:46 UTC, stvstnfrd commented on setup.py
> +    description="Enables instructors to add numeric input problems with '\
Use parens and implied concatenation over backslashes.

2017-07-19 21:46 UTC, stvstnfrd commented on requirements.txt
> +-e .
Why don't we list the other modules listed in `install_requires`?

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +        self.assertIsNotNone(test_result.get('score'))
Don't bother checking `None` if you're comparing the actual value below.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +        self.assertTrue(test_result.get('score'))
This is unnecessary, given the following check.

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +        # Remove unused keys to help test the lists
Why though?

2017-07-19 21:46 UTC, stvstnfrd commented on adaptivenumericinput/tests.py
> +        self.assertEquals(result_title, test_result[0][0])
Why are we testing this? Do we actually care what the title is?

2017-08-01 21:47 UTC, caseylitton commented
![](https://github.trello.services/images/mini-trello-icon.png) [xblock-ify numeric input Adaptive Hint problem](https://trello.com/c/taCor6Qw/537-xblock-ify-numeric-input-adaptive-hint-problem)

2017-08-01 21:47 UTC, caseylitton commented
![](https://github.trello.services/images/mini-trello-icon.png) [xblock-ify numeric input Adaptive Hint problem](https://trello.com/c/taCor6Qw/537-xblock-ify-numeric-input-adaptive-hint-problem)

2017-08-01 21:47 UTC, caseylitton commented
![](https://github.trello.services/images/mini-trello-icon.png) [xblock-ify numeric input Adaptive Hint problem](https://trello.com/c/taCor6Qw/537-xblock-ify-numeric-input-adaptive-hint-problem)

2019-08-08 03:01 UTC, merged